### ISSUE TITLE
"Requires additional permissions - Sandbox escape"

### ISSUE THREAD

**Issue by x11x** [flathub/com.vscodium.codium#150]
Hi,
I would like to read about what change(s) lead to this new permission being required in 1.73.1.22314

> Sandbox escape
> Can escape the sandbox and circumvent any other restrictions

Is there an issue or discussion somewhere I can read about this change? Sorry if I have missed somewhere obvious.
Maybe this is something new in flatpak itself? since as far as I know this has always been possible using `flatpak-spawn --host`.
Would appreciate any links.
Thank you

**Comment by noonsleeper** [comment]
Hi @x11x, Can you point me to where do you found that?

**Comment by RalfJung** [comment]
Maybe the software center got a new feature to display these additional permissions?

This flatpak *does* ask for `--talk-name=org.freedesktop.Flatpak` which is indeed a complete sandbox escape.

**Comment by noonsleeper** [comment]
@x11x, flatpak-codium has the same permission since it was created (and I have to say that has fewer permissions that the binary install directly on system-side).

This is a code editor you need to perform some tasks that need access to your filesystem or to execute something on your host system, I think those permissions have some kind of logical to the task for what was created codium.

**Comment by noonsleeper** [comment]
I wonder if gnome software say the same for the rpm or deb packages, or even for any other text editor like vim that has the same functionality (I mean you can execute things from vim), but aren't inside a container?

**Comment by RalfJung** [comment]
Personally I am using flatpak over deb/rpm because I want the proper container, so I do appreciate these warnings. Nobody expects any isolation from deb/rpm, but with flatpak the expectations are higher. If I didn't care about the sandbox I would just install the official deb... (And I have added local `flatpak override` to prevent these sandbox escapes.)

**Comment by noonsleeper** [comment]
@RalfJung I mean for the most of the people that install a new code/text editor hardening to the complete isolations as default is a nuance, if they install a code editor they want to edit some files and maybe run those files on the inner terminal. The thing that they don't want is to read about the whole isolation system that a container like flatpak has to unlock the home directory.

And don't get me wrong, I'm the first that apply a more hardening policy to flatpak codium using the override system or flatseal that is a wonderful tool to see what permissions have any flatpak app that you install, I'm just saying that we need to understand that this is a code editor and need some permissions in order to work as expected for the new folks.

Also, the readme explains about that topic, then anybody that install for the firs time codium have access to the info about how to harden the container thanks to you =).

**Comment by x11x** [comment]
Thanks for both of your comments, that is all helpful information.
@noonsleeper that answers my question, confirming that permissions have not actually changed. Something must have changed in gnome-software.

Yes, I agree, these permissions are logical and expected - and clearly necessary for any IDE or terminal. I was just confused why gnome software was reporting a permission change. And yes, I believe the vim flatpak needs the same set of permissions (and all terminals/IDEs I checked)

Thanks @RalfJung for your recent readme contributions, they are helpful for discovering how you can get a higher level of sandboxing.

The way gnome software reports permissions and safety is slightly confusing I think.
I'm not sure what it says about the vscodium RPM. I know it marks the official system RPMs as "safe" even though they have no sandbox or configurable "permissions" at all. They are considered "safe" due to being in the official repos and reviewed by OS maintainers. I think this is a little misleading and confusing and because - as you say - the flatpak only has the same or less permissions than an rpm/deb, its not more "unsafe". However, on the other hand, flatpaks are usually from 3rd-party, so I guess this is why their "safety" is judged on different criteria.

Will close because my question has been answered.
