### ISSUE TITLE
VsCodium vs VsCode Flatpak size

### ISSUE THREAD

**Issue by bluesangel** [flathub/com.vscodium.codium#187]
Hello,
Not sure this can be considered as a bug, maybe rather a feature request. 
Comparing VsCodium vs VsCode Flatpak size I see a huge difference : 

```
$ flatpak list --app --columns=application,version,runtime,size  | grep -i cod
com.visualstudio.code	1.77.3-1681292746	org.freedesktop.Sdk/x86_64/22.08	10,2 Mo
com.vscodium.codium	1.77.3.23102	org.freedesktop.Sdk/x86_64/22.08	        295,6 Mo

```
Can something be done to reduce/optimize the size of VsCodium Flatpak ? 

Thanks
Stéphane.

**Comment by abitrolly** [comment]
@bluesangel for me the bigger issue is 1.5Gb dependency on Freedesktop SDK #192.

**Comment by noonsleeper** [comment]
Hi @bluesangel, I comment something about this on https://github.com/flathub/com.vscodium.codium/issues/192.

**Comment by GitMensch** [comment]
Even with that dependency:

* What dependencies does `com.visualstudio.code` have?
* Any insights why `com.vscode.codium` is that bigger?

**Comment by larina3315** [comment]
> Even with that dependency:
> 
>     * What dependencies does `com.visualstudio.code` have?
> 
>     * Any insights why `com.vscode.codium` is that bigger?

I am not experienced in dealing with flatpak development/packaging, but comparing the .yaml files for VSCodium vs VSCode, it has come to my attention that...
- VSCode's .yaml file contains an extra line (base: org.electronjs.Electron2.BaseApp) (https://github.com/flathub/com.visualstudio.code/blob/master/com.visualstudio.code.yaml)
- VSCodium's .yaml file lacks the base: line (https://github.com/flathub/com.vscodium.codium/blob/master/com.vscodium.codium.yaml)
- Checking the flatpak docs for Base apps, it appears to me VSCode uses the bundled electron from Freedesktop platform, while VSCodium bundles it's own electron (?)

links to the docs :
- https://docs.flatpak.org/en/latest/dependencies.html#base-apps
- https://docs.flatpak.org/en/latest/electron.html#the-electron-base-app

**Comment by abitrolly** [comment]
@larina3315 good catch! Using common base can definitely help reduce installation size.

**Comment by larina3315** [comment]
> > i packaged the .test version locally with the base: option and it had zero impact on the size
> 
> @larina3315 maybe there should be several flatpaks sharing the same base for the savings.

I believe the difference ultimately boils down to the fact that the VSCodium flatpak repackages the deb inside the flatpak itself while creating the flatpak
While the VSCode flatpak downloads the .deb file upon installation

@noonsleeper I believe this issue can be closed

**Comment by noonsleeper** [comment]
Today I test this again and `flatpak list --app --columns=application,version,runtime,size  | grep -i code` report this

![Screenshot from 2024-06-02 22-12-10](https://github.com/flathub/com.vscodium.codium/assets/62183384/14a5ca59-d588-4c82-9b7d-0470c41c21ec)

and inside the container, you can see that the binary size is bigger than 15Mb
![Screenshot from 2024-06-02 22-13-11](https://github.com/flathub/com.vscodium.codium/assets/62183384/136a20dc-9a53-4a2e-9279-09bff36ebfde)

Then the size is more or less the same for code, code-oss and even vscodium.

I will close this since I don't see a big difference in size that's worth the effort.

If you have another problem, don't hesitate, and open a new issue.
