### ISSUE TITLE
It won't open

### ISSUE THREAD

**Issue by RaptaG** [flathub/com.vscodium.codium#199]
```
[raptag@desktop raptag]$ flatpak run --branch=stable --arch=x86_64 --command=/app/bin/codium --file-forwarding com.vscodium.codium --unity-launch @@ %F @@
codium-wrapper: Setting up NPM packages
codium-wrapper: Setting up Cargo packages
codium-wrapper: Setting up Python packages
codium-wrapper: Setting up Ruby packages
```

Running Fedora Kinoite 38

**Comment by RaptaG** [comment]
@noonsleeper you seem to be the maintainer of this Flathub distribution of VSCodium. This is a critical bug, making the app unusable, could you fix it?

**Comment by noonsleeper** [comment]
@RaptaG Hi, maybe is only not working for you and no to everyone. 

> This is a critical bug, making the app unusable
In the future, try to avoid this kind of statements when you need help.

Then can you show to us the output of `flatpak run com.vscodium.codium --verbose` and `flatpak override --user --show com.vscodium.codium`, are you try to launch this on wayland? Or, are you try to run first `flatpak repair`?

**Comment by RaptaG** [comment]
Hello and thanks for the response!

> are you try to launch this on wayland

Yes, is the permission disabled/should I force-enable x11 on its Flatpak permissions? I totally forgot to check that :skull:

**Comment by noonsleeper** [comment]
The short answer:
Yes, activate `socket=x11`, `flatpak override --user --socket=x11 com.vscodium.codium`.

The long answer:
due to this https://github.com/microsoft/vscode/issues/167757 we can't activate wayland as default, but you can use it following these steps: 

```
flatpak override --user --nosocket=x11 --socket=wayland com.vscodium.codium
```

from the terminal, try to launch codium:
```
flatpak override run com.vscodium.codium --ozone-platform-hint=auto
```

also, you can customize the `.desktop` files
```
cp /var/lib/flatpak/exports/share/applications/com.vscodium.codium*.desktop /var/home/$USER/.local/share/applications/
```
add `--ozone-platform-hint=auto` on the `Exec=` line before the last `@@ %F @@` or `--open-url @@u %U @@` and then update the desktop-database with `update-desktop-database --verbose /var/home/$USER/.local/share/applications/`
