### ISSUE TITLE
Add --ozone-platform-hint=auto for decied X11 or Wayland

### ISSUE THREAD

**Issue by barni2000** [flathub/com.vscodium.codium#202]
It would be great if --ozone-platform-hint=auto is added to the start.
This parameter is enable auto wayland detection.

**Comment by warriormaster12** [comment]
@barni2000  @noonsleeper And unfortunately with vscodium this removes the ability to have global menu when using native wayland. Not sure if this needs to be reported to vscode since some electron apps seem to have global menu even in wayland. For now, where can I look for this argument ```--ozone-platform-hint=auto``` so that I can force the editor to run in XWayland.
