### ISSUE TITLE
Using another shell

### ISSUE THREAD

**Issue by jeffteixeira** [flathub/com.vscodium.codium#37]
Is it possible to use another shell in the integrated terminal inside the sandbox?

**Comment by jeffteixeira** [comment]
something like that: https://github.com/flathub/com.visualstudio.code.tool.fish

**Comment by noonsleeper** [comment]
yeah! @jeffteixeira I think is a great idea =)

**Comment by jeffteixeira** [comment]
I tested this one but it didn't work. Apparently it only works with VSCode and Code-OSS @noonsleeper

**Comment by jeffteixeira** [comment]
This extension does not work with VSCodium, only with VSCode and Code-OSS.

**Comment by gasinvein** [comment]
Does it make sense to change the extension point from `com.vscodium.codium.tool` to `com.visualstudio.code.tool`, so that the same extensions could be plugged into VSCodium as well?
Obviously existing extensions under `com.vscodium.codium.tool` namespace would stop working, but there are none on Flathub.

**Comment by noonsleeper** [comment]
Hey @jeffteixeira now you can use https://github.com/flathub/com.visualstudio.code.tool.fish in vscodium as well

**Comment by noonsleeper** [comment]
@jeffteixeira I'll close this since this solve the issue.

**Comment by awebeer256** [comment]
I'm coming in long after the fact to point out that you also need the correct *version* of `com.visualstudio.code.tool.fish`, or else it'll be as if you didn't install it at all. One of the distros I use currently ships fish 3.5.1, so I installed `runtime/com.visualstudio.code.tool.fish/x86_64/21.08`, because that version of the runtime also ships fish 3.5.1. But it just didn't work. I had to install `runtime/com.visualstudio.code.tool.fish/x86_64/22.08`, corresponding to fish 3.6.1, instead.

Hopefully this will save someone else some grief.
