### ISSUE TITLE
integrated shell not reading my .profile 

### ISSUE THREAD

**Issue by goldcoders** [flathub/com.vscodium.codium#5]
Im trying to use the flatpak version of vscodium 
but Im having trouble with integrated shell
```json
"terminal.integrated.shell.linux": "/usr/bin/env",
    "terminal.integrated.shellArgs.linux": [
        "--",
        "flatpak-spawn",
        "--host",
        "zsh",
    ]
```
It seems my .profile and .config/zsh/.zshrc is not being source when i run flatpak-spawn 
also the TERM variable is not set , which is define in my .profile...

but if do 
source ~/.profile and source ~/.config/zsh/.zhrc

Then all my shortcuts in my terminal is back...

Is there a way i can source it without doing it manually?

**Comment by noonsleeper** [comment]
Hi, usually zsh read config (depending on distro, but for archlinux) from ~/.zshenv, ~/.zprofile, ~/.zshrc, ~/.zlogin, ~/.zlogout not for  ~/.config/zsh/ directory could you try to move files to this path and try again?, also the profile name for zsh usually is .zprofile instead of .profile

For the TERM variable I recommend that you set the value that your prefer.
I added to the first line of ~/.zshrc `export TERM=xterm` that does the trick for me

**Comment by noonsleeper** [comment]
Hi @goldcoders I will close this issue due to a long period of non response. If you still having problems with, please open a new ticket too. =)
