### ISSUE TITLE
Signed commits with GPG does not work

### ISSUE THREAD

**Issue by tommytran732** [flathub/com.vscodium.codium#53]
VSCodium cannot seem to sign any commits if the GPG key has a passphrase. If the key does not have a passphrase, it works fine. If the key has a passphrase but is already unlocked with the GPG agent (by doing git commit directly on the host and type in the passphrase once), then it can also sign the commits.

I think this is due to the lack of pinentry, so I hope you could have a look.

**Comment by noonsleeper** [comment]
@rugk your solution is like my approach to shellcheck =)

https://github.com/flathub/com.vscodium.codium/issues/26#issuecomment-739291303

**Comment by rugk** [comment]
Sure, in fact I also have an simple script for `shellcheck` in there:
https://github.com/rugk/atom-flatpak-wrapper/blob/master/flatpak-shellcheck.sh

**Comment by noonsleeper** [comment]
Hey @tommytran732, I'll close this ticket because has many months without updates, If you have another problem doesn't hesitate and open a new Issue.

**Comment by GeoffreyCoulaud** [comment]
Hey @noonsleeper I just ran into this issue, maybe we should include the fixes proposed by @rugk by default since it's not fixed ?

**Comment by noonsleeper** [comment]
@GeoffreyCoulaud, the solution of @rugk is a set of scripts that you need to take care on your host, not be included inside the container look on the [rugk's repo](https://github.com/rugk/atom-flatpak-wrapper).

Please, if you have questions, open a new issue and point to the older issue instead of comment on the previously closed.
