### ISSUE TITLE
Document how to modify product.json

### ISSUE THREAD

**Issue by itspngu** [flathub/com.vscodium.codium#90]
I just spent about half an hour reading through Github issues and source code of VSCode & VSCodium to figure out how to get Pylance working. In short:

- The workaround described [here](https://github.com/VSCodium/vscodium/issues/892#issuecomment-986663776) suggests editing a `product.json` file, but `find $HOME/.var/app/com.vscodium.codium -name 'product.json'` returns nothing
- Found #22 which links to https://github.com/VSCodium/vscodium/pull/674
- The linked PR contains a [patch](https://github.com/VSCodium/vscodium/blob/3277bd4fa19f262fa1d1a1fb916b4d6d9e0bd134/patches/custom-gallery.patch#L35) which looks for a user-provided `product.json` *to merge into* the compiled-in values - by default, no `product.json` is included in shipped builds
- Dropping the following file into `$HOME/.var/app/com.vscodium.codium/config/VSCodium/product.json` lets me run Pylance:

```
{
  "nameShort": "Visual Studio Code",
  "nameLong": "Visual Studio Code",
  "extensionsGallery": {
    "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
    "cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",
    "itemUrl": "https://marketplace.visualstudio.com/items"
  }
}
```

As this is a rather specific workaround to a specific problem, perhaps just including a note somewhere is enough to spare others from having to go through the same journey.

**Comment by mpauper** [comment]
Just here to say that if I am not mistaken, this is technically illegal.

**Comment by bxff** [comment]
Also refer: https://github.com/VSCodium/vscodium/issues/940#issuecomment-1341932901

**Comment by r1jsheth** [comment]
> Just here to say that if I am not mistaken, this is technically illegal.

very curious being a newbie, how is it technically illegal to document this?

**Comment by GitMensch** [comment]
While I think you are kidding even without an explicit smiley: anyone is free to document this, but both using Pylanc and the MS marketplace means you need to follow their license - which explicit says that the license only allows those to be used with Microsoft products (and Microsoft made quite clear that "vscode-oss builds" don't match that description).

It would therefore be most reasonable to document that instead of any hacks one should use https://github.com/flathub/com.visualstudio.code if one wants to use these Microsoft services and (binary-only distributed) extensions.
