### ISSUE TITLE
Unable to use sudo in the integrated terminal

### ISSUE THREAD

**Issue by GeoffreyCoulaud** [flathub/com.vscodium.codium#91]
It's impossible to use `sudo` in the integrated terminal.  
Maybe there is a misconfiguration with the terminal subprocess' streams ? 

An error is spat out :  
```
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
```

Edit : 
The error message is mentionned on [sudo's FAQ](https://www.sudo.ws/docs/troubleshooting/#when-i-try-to-run-sudo-via-ssh-i-get-an-error) but it's related to SSH. 

> If sudo needs to authenticate a user, it requires access to the user’s terminal to disable echo so the password is not displayed to the screen. The above message indicates that no terminal was present.

**Comment by noonsleeper** [comment]
Hey @GeoffreyCoulaud sorry the late response.

I think, I remember is not possible to run `sudo` inside a flatpak container because [this](https://github.com/containers/bubblewrap#security)
but maybe someone a more enlighten response to this.

But you can run `flatpak-spawn --host sudo -S sudo <COMMAND>` to get a some kind of.

I think the better is to use the terminal of your host like [this](https://github.com/flathub/com.vscodium.codium#host-shell).

**Comment by GeoffreyCoulaud** [comment]
No worries :)

Yup this makes sense. However, even in the host terminal I get this message. 
Here's my terminal profile : 

```json
    "terminal.integrated.defaultProfile.linux": "zsh",
    "terminal.integrated.profiles.linux": {
        "bash": {
            "path": "/usr/bin/flatpak-spawn",
            "args": ["--host", "--env=TERM=xterm-256color", "bash"]
        },
        "zsh": {
            "path": "/usr/bin/flatpak-spawn",
            "args": ["--host", "--env=TERM=xterm-256color", "zsh"]
        }
    }
```

It seems like the sandbox doesn't expose the host terminal properly... Well at least it could be that

**Comment by noonsleeper** [comment]
Hey @GeoffreyCoulaud, I'll close this, if you have another problem, don't hesitate and open a new issue.
